[features]
seeds = false
skip-lint = false
[programs.devnet]
sol_transfer = "233b2ADNn7Jam3WzYkF44bdPWuTYr7iEt1vd4K4y3J91"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/nitenl619/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
